grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
      n_estimators: 64
      learning_rate: 0.05
      max_depth: 4
      min_samples_leaf: 3
      subsample: 0.75
    search_param_grid:
      n_estimators:
      - 50
      - 60
      - 70
      learning_rate:
      - 0.03
      - 0.05
      - 0.07
      max_depth:
      - 4
      - 5
      - 6
      min_samples_leaf:
      - 3
      - 4
      - 5
      subsample:
      - 0.73
      - 0.75
      - 0.78

  module_1:
    class: SVC
    module: sklearn.svm
    params:
      random_state: 42
      C: 1000
      gamma: 0.01
      kernel: rbf
    search_param_grid:
      C:
      - 100
      - 500
      - 1000
      gamma:
      - 0.08
      - 0.05
      - 0.01
      kernel:
      - rbf
